### ISSUE TITLE
jQuery conflict - due to Object.prototype

### ISSUE THREAD

**Issue by mczlowiek** [jhpratt/skrolr#7] opened 2016-12-02 07:15 UTC
I have problem with skrolr.js. When I put it on a website other scripts don't work properly.
For example: menu does not work
site: http://chks.chotow.pl/beta

**Comment by jhpratt** [comment] 2016-12-02 16:28
There shouldn't be any conflicts, as everything is prefixed with either `skrolr_` or `skrolr-`. Regardless, I'll take a look at it this weekend.

**Comment by jhpratt** [comment] 2016-12-02 21:58
Just took a good look through all the JS. There are no conflicts; the menu not working is unrelated to *skrolr*. However, I did find some issues that I previously never noticed (due to varying implementations).

**Comment by mczlowiek** [comment] 2016-12-03 08:41
hi, but when i disable skrolr then all other scripts work propertly

**Comment by jhpratt** [comment] 2016-12-03 22:25
Ah, I didn't try that. I've actually never run into this issue, but it's actually been a major issue within the jQuery codebase for years. jQuery is completely incompatible with prototype extensions, even if they do nothing.

This will require a significant portion of the code to be rewritten, so this won't be done for a few weeks at the earliest. I have quite a bit going on in the next two weeks, but after that I'll be able to make the necessary changes. I can probably have this done be year-end, but that may be optimistic.

Essentially, I will have to rewrite the prototypes into OOP. I may be overthinking the requirements (in fact, I likely am). **On the off chance someone is reading this and is interested in making the changes, please do so!** I'll happily look over a pull request.

**Comment by jhpratt** [comment] 2016-12-10 22:40
I just updated *skrolr* basic, though I have not tested this implementation with jQuery. I believe it works, so feel free to check it out if you want. It's located on the [rewrite-basic branch](https://github.com/jhpratt/skrolr/tree/rewrite-basic).

**Comment by mczlowiek** [comment] 2016-12-12 06:42
don't work...

**Comment by jhpratt** [comment] 2016-12-14 00:00
I just swapped out the required bits of code on your site, and it works as expected. It's just the basic version, so all the "fancy" stuff would have to be done yourself. My first real opportunity to work on rewriting the codebase will be this coming weekend. However, I'm also working on a large proposal, which will take much of my time.

I'll keep you posted on the rewrite status.

**Comment by mczlowiek** [comment] 2016-12-15 07:54
still dont work. Maybe i can give You acces to my ftp, and You can check it?

**Comment by jhpratt** [comment] 2016-12-16 00:29
For anyone that is looking at the thread, communication regarding the implementation has shifted to email, as it's not relevant to *skrolr* in general.

**Comment by jhpratt** [comment] 2017-04-07 03:57
@mczlowiek On the off chance you're still looking to use this library, check out the ts-rewrite branch. It _should_ work with jQuery, and is currently missing minimal functionality. However, I haven't tested it with jQuery yet.

**Comment by jhpratt** [comment] 2017-05-07 01:02
Current TypeScript build (0256052) works with jQuery 3.2.1. Only build tested so far.

**Comment by jhpratt** [comment] 2017-05-08 20:01
Confirmed working with jQuery 3.2.1 in both ES6 and ES3 (in cb6429f). Closing this issue.

**Closed by jhpratt** 2017-05-08 20:01 UTC
Labels: Priority: High, Status: In Progress, Type: Bug
